### ISSUE TITLE
Preserve playlist options

### ISSUE THREAD

**Issue by porg** [marcrobledo/retroarch-playlist-editor#19]
## Reproduction

1. Import a playlist in version 1.5 format which also has playlist options like this:
```json
{
  "version": "1.5",
  "default_core_path": "…",
  "default_core_name": "…",
  "label_display_mode": 5,
  "right_thumbnail_mode": 0,
  "left_thumbnail_mode": 0,
  "sort_mode": 0,
  "items": [
    {… }, {… }, {… },  # Playlist items
  ]
}
```
2. Perform your playlist operations.
3. Click "Save playlist".
4. Inspect the resulting playlist.

## Actual
- The playlist options are lost on export.

## Expected
- The playlist options (in the JSON "header" before the "items" array) is preserved in the export.
- If you drag-n-drop multiple playlists (consecutively) onto Playlist Editor, it takes the options of the first playlist that was dropped. Otherwise you would need to take care of how to unite the options, which would need quite some logic or user intervention.
- As soon as the second playlist is dropped, throw a toast message (of severity "info", the ones which disappear by themselves after a timeout) like this:

  **Imported more than 1 playlist**
  - ROM items from multiple playlists got merged successfully.
  - But playlist options are only considered from the first playlist.

## Workaround
- Export playlist. Then re-insert the header snippet from a backup of the playlist. Save.

## Screenshot
![Playlist v1.5 and how its exported as v1](https://user-images.githubusercontent.com/737143/153861139-fca4b185-761a-47ae-beaa-695c9b95f3a7.png)

**Comment by marcrobledo** [comment]
Done!
