### ISSUE TITLE
Offer export option "Keep core as-is" (core_path and core_name remain unchanged)

### ISSUE THREAD

**Issue by porg** [marcrobledo/retroarch-playlist-editor#20]
- In case of someone just merging playlists, it's best to just keep it as is!
- Instead of trying to normalize, but instead break it, which is the case in your hosted web app of 2022-02-14.
- So please at least just offer the option "Keep core as-is"
- Currently you only offer concrete core-schemes or DETECT, but no "keep as-is" option.

<img width="1120" alt="Playlist export option core as Android" src="https://user-images.githubusercontent.com/737143/153861516-73495930-636d-4991-9cc8-6d2c86bd984d.png">

<img width="1120" alt="Playlist export option core as DETECT" src="https://user-images.githubusercontent.com/737143/153861544-46f5a42a-0b50-4b35-805b-a9f213f00242.png">

![Playlist v1 5 and how its exported as v1](https://user-images.githubusercontent.com/737143/153861139-fca4b185-761a-47ae-beaa-695c9b95f3a7.png)

**Comment by marcrobledo** [comment]
What would be the advantages for this?

Any time you add/merge a playlist, its content's core path are added to the select dropdown (and selected automatically). So the core paths are kept.
Unless you want to mix various different core paths in a single playlist, but I don't think no one wants to do that.

**Comment by porg** [comment]
Submission of my issue is already 2 months ago, so I hope I recall correctly, but AFAIR:
- On save the app forces you to set the core path.
  - If there is no "Keep core as-is" option this effectively always enforces a core normalization.
- Which is not desired for all situations. Say 2-3 games shall particularly be run in core_X and all others in core_Y, be it performance or realism, or multiplayer support only working here but not there, or whatever reason, but these differentiated preferences indeed exist in emulation reality still to that day. It is really the reason you stated:
> Unless you want to mix various different core paths in a single playlist, but I don't think no one wants to do that.

**Comment by marcrobledo** [comment]
I've got a Mega Man playlist with various NES, SNES and PSX cores made with (the now old!) Retroarch Playlist Editor and it works flawlessly.
As long as all cores are installed under the same directory, you can use mixed cores in the same playlist. When saving the playlist, the chosen core path gets the `*` replaced with the content core filename when saving the playlist.

**Comment by porg** [comment]
Cool! So you implemented the feature.

How is this shown to the user?
Core Path: [ Keep core as-is  ▾ ]

**Comment by marcrobledo** [comment]
This was already implemented. User doesn't need to do anything but choose the playlist core path for his/her device. All core file names will be set correctly when saving.
