### ISSUE TITLE
Export options db_name must be left as-is so that thumbnails are shown for mixed system playlist (cross-platform or cross-folder ROMs)

### ISSUE THREAD

**Issue by porg** [marcrobledo/retroarch-playlist-editor#21]
The web app as hosted as of 2022-02-14 transforms `db_name` to that of the playlist name.
- That is wrong. But no wonder, because the user documentation on this was wrong!
  - Which I found out by experimentation, and meanwhile already updated the user docs accordingly.
  - My version is [here for reference](https://github.com/porg/docs/blob/patch-2/docs/guides/roms-playlists-thumbnails.md#creating-custom-playlists-cross-platform-cross-folders) and meanwhile it was already accepted to the [official user docs](https://docs.libretro.com/guides/roms-playlists-thumbnails/#creating-custom-playlists-cross-platform-cross-folders)
- The key finding, which is relevant for this issue:
> The `db_name` attribute entry must be the ROM's corresponding `Exact Game Platform Playlists Name.lpl` (e.g. `Nintendo - Game Boy.lpl`) in order to be associated with the correct metadata and thumbnails.

- Here is a screenshot which shows that `db_name` gets set to `Name of the new playlist.lpl` which will result in thumbnails and metadata not being found in your custom created playlist:
![Playlist v1 5 and how its exported as v1](https://user-images.githubusercontent.com/737143/153861139-fca4b185-761a-47ae-beaa-695c9b95f3a7.png)

**Comment by marcrobledo** [comment]
Done!
