### ISSUE TITLE
Edit content shall only open on double click (pointer devices) or long-press (touch devices)

### ISSUE THREAD

**Issue by porg** [marcrobledo/retroarch-playlist-editor#23]
- As of 2022-02-14 the "Edit Content" dialog opens on single click.
- This assumes that "Edit content" is the main and only function of Playlist Editor.
- Which it is not!
 
Selecting to then move or delete is as important!
- And in order to do this you currently always have to click, then close the dialog by mouse or ESC. Only then resume.
- Quite cumbersome

Proposal
- Single click only selects
- Double click (on pointer devices) or long-press (on touch devices) opens the "Edit Content" dialog

**Comment by marcrobledo** [comment]
Done.

Since the UI has changed slightly, implementation will be a little different:
The edit dialog still opens automatically, but user can close it manually and it won't open automatically next time. The original behaviour can be restored just by opening the dialog manually again.

**Comment by porg** [comment]
Persistent mode switching is an acceptable UX too. 👍
