### ISSUE TITLE
Allow to extend selection by clicked item

### ISSUE THREAD

**Issue by porg** [marcrobledo/retroarch-playlist-editor#25]
**Reproduction**
- You have an active selection (possibly by help of #24)
- You want to extend it by certain single non-consecutive items

**Actual**: Not possible

**Expected**: Click with modifier-key down (cmd on Mac, ctrl on Window/Linux)

**User Rationale:** Select multiple items to move or delete, a quite frequently used function in any playlist editor

**Comment by marcrobledo** [comment]
Which web browser and OS are you using? This has been implemented since first version.

**Comment by marcrobledo** [comment]
Wait. I see the uploaded version is not working correctly, my mistake.

This has been already fixed for next version.

**Comment by porg** [comment]
✅ Tested and worked on: Safari 15.4 on macOS 11.6.5
