### ISSUE TITLE
Chokes on playlist files containing JSON comments

### ISSUE THREAD

**Issue by porg** [marcrobledo/retroarch-playlist-editor#26]
## Reproduction
- Import a LPL file in JSON format which has some comments in it

## Actual
- Playlist Editor as of 2022-02-14 chokes on them, you get a broken list.

## Expected
- Minimum fix: Drop all comments during import.
  - Machine produced playlists likely not contain them.
  - But you never know, maybe some playlist apps use comments to add proprietary tags or user comments that way.
  - Or users put manual remarks their.
- Better: Drop all comments which are on their own lines. Hard to determine to which part the supposedly belong too, when reordering items. But keep the comments which are at the end of a line after the respective key/value pair. Clear that it belongs their. Not necessary. If do-able without too much effort maybe a convenient options, if some users may keep remarks regarding ROMs like this.
- Best: Keep all comments. But requires some logic. Overkill IMHO.

## Screenshot

<img width="1440" alt="Playlist Editor chokes on playlist files with JSON comments" src="https://user-images.githubusercontent.com/737143/153881348-f40034e0-19c4-48ee-8be9-3730b2359dfc.png">

## Sample file Playlist-with-comments.lpl

```json
{
  "version": "1.5",
  "label_display_mode": 3,
  "right_thumbnail_mode": 0,
  "left_thumbnail_mode": 0,
  "sort_mode": 0,
  "items": [
    {
      "path": "1",            // Comment after the key/value pair.
      "label": "Game 1",           // Comment after the key/value pair.
      "core_path": "/data/user/0/com.retroarch.aarch64/cores/duckstation_libretro_android.so",
      "core_name": "Sony - PlayStation (DuckStation)",
      "crc32": "1",           // Comment after the key/value pair.
      "db_name": "Sony - PlayStation.lpl"
    },
    {
      "path": "2",
      "label": "Game 2",
      "core_path": "/data/user/0/com.retroarch.aarch64/cores/duckstation_libretro_android.so",
      "core_name": "Sony - PlayStation (DuckStation)",
      "crc32": "2",
      "db_name": "Sony - PlayStation.lpl"
    },

      // Comment on its own line. Not so easy to determine to which JSON element it belongs.

    {
      "path": "7",
      "label": "Game 3",
      "core_path": "/data/user/0/com.retroarch.aarch64/cores/mupen64plus_next_gles3_libretro_android.so",
      "core_name": "Nintendo - Nintendo 64 (Mupen64Plus-Next)",
      "crc32": "",
      "db_name": "Nintendo - Nintendo 64.lpl"
    },
    {
      "path": "8",
      "label": "Game 4",
      "core_path": "/data/user/0/com.retroarch.aarch64/cores/duckstation_libretro_android.so",
      "core_name": "Sony - PlayStation (DuckStation)",
      "crc32": "8",
      "db_name": "Sony - PlayStation.lpl"
    }
  ]
}
```

**Comment by stefangabos** [comment]
JSON doesn't support comments
https://stackoverflow.com/questions/244777/can-comments-be-used-in-json#:~:text=JSON%20does%20not%20support%20comments,configuration%20file%20format%20for%20humans.

**Comment by porg** [comment]
Ok. Thanks for the info.

Closing this issue as irrelevant then.

Anyhow did not occur in a real world scenario but with a manually adapted test file.
