### ISSUE TITLE
JSON syntax error, missing escape character

### ISSUE THREAD

**Issue by waitingmoon** [marcrobledo/retroarch-playlist-editor#27]
![json_escape](https://user-images.githubusercontent.com/16256443/169790902-cc93a6a1-d382-4b40-8424-ccf5c8a9a77c.jpg)

Specifying default core path in RetroArch Playlist Editor strips escape characters from the `default_core_path`. A syntax error will occur and all entries will be lost. The lpl below was created within RetroArch.

**Comment by marcrobledo** [comment]
fixed in 2418179f2439604c89b6c6c08836bef81b2cbfab

Thank you!
